version: 2.1

parameters:
  task:
    type: enum
    enum: ['build', 'deploy']
    default: 'build'
  build_stage:
    type: enum
    enum: ['dev', 'prod']
    default: 'dev'

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/map-sorter-api
    environment:
      DOCKER_IMAGE: high10hunter/map-sorter-api
      DOCKER_TAG: latest
    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build and push image
          command: |
            echo "Building image"
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

            echo "Pushing image"
            docker push $DOCKER_IMAGE:$DOCKER_TAG

            echo "::set-output name=image::$DOCKER_IMAGE:$DOCKER_TAG"

  deploy:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/map-sorter-api
    environment:
      DOCKER_IMAGE: high10hunter/map-sorter-api
      DOCKER_TAG: latest
    steps:
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc-provider-aws'
          aws-region: AWS_REGION
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 'SHA256:+2S1UpsWHcjQu4ur9jpqF16GQa9NrND9qbFNU6pzB64'

      - run:
          name: Create .env file and sync to dev server
          command: |
            cd tools
            aws ssm get-parameters-by-path --path "/dev" --with-decryption --recursive > mapsorter_env.json
            ./convert_ssm_params_to_dotenv.sh mapsorter_env.json
            scp -oStrictHostKeyChecking=no -v -r .env $SSH_USER@$SSH_HOST:/home/gdsc/map-sorter-api/.env

      - run:
          name: SSH into dev server and deploy
          command: |
            echo "SSH into dev server"
            ssh -o StrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "
              su - gdsc -c '
                cd map-sorter-api &&
                echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin &&
                docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
                docker container stop map-sorter-api || true &&
                docker container rm map-sorter-api || true &&
                docker run --log-opt max-size=10m --log-opt max-file=3 --log-opt compress=true \
                          --name map-sorter-api -d --env-file .env $DOCKER_IMAGE:$DOCKER_TAG &&
                docker image prune --all -f
              '
            "

workflows:
  version: 3
  Build:
    # if the 'task' parameter equals 'build' then run Build workflow
    when:
      equal: [build, << pipeline.parameters.task >>]
    jobs:
      - build:
          filters:
            branches:
              only: develop

  DeployDev:
    # if the 'task' parameter equals 'deploy'
    # and the 'build_stage' parameter equals 'dev' then run DeployDev workflow
    when:
      and:
        - equal: [deploy, << pipeline.parameters.task >>]
        - equal: [dev, << pipeline.parameters.build_stage >>]
    jobs:
      - build
      - deploy:
          context: aws
          requires:
            - build
          filters:
            branches:
              only: develop

  DeployProd:
    # if the 'task' parameter equals 'deploy'
    # and the 'build_stage' parameter equals 'prod' then run DeployProd workflow
    when:
      and:
        - equal: [deploy, << pipeline.parameters.task >>]
        - equal: [prod, << pipeline.parameters.build_stage >>]
    jobs:
      - build
      - deploy:
          context: aws
          requires:
            - build
          filters:
            branches:
              only: main
