name: Build
on:
    pull_request_review:
        types: [submitted]

jobs:
    build:
        if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Trigger Build workflow on CircleCI
              run: |
                  curl \
                      -X POST \
                      -H "Content-Type: application/json" \
                      -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
                      --data '{"branch": "develop", "parameters": {"task": "build"}}' \
                      https://circleci.com/api/v2/project/gh/dscdut/map-sorter-api/pipeline
